const ROTATIONS=['P1','P6','P5','P4','P3','P2'];
const PHASE={serve:'BATTUTA',receive:'RICEZIONE'},SHORT={serve:'B',receive:'R'};
const KEY='sir_matchup_web_v3';
const SLOTS=['P','S1','C2','O','S2','C1','L'];
const SLOT_ROLE={P:'S',S1:'OH',S2:'OH',C1:'MB',C2:'MB',O:'OP',L:'L'};
const BASE_P1={1:'P',2:'S1',3:'C2',4:'O',5:'S2',6:'C1'};
const blank={seasons:[],competitions:[],teams:[],selectedTeamId:null,filters:{seasonId:'',competitionId:''},match:{seasonId:'',competitionId:'',ourTeamId:null,oppTeamId:null,ourPhase:'serve',ourRotation:'P2',oppRotation:'P1'},quick:{queryPhase:'receive',queryRotation:'P4',desiredOurPhase:'receive',desiredOurRotation:'P5',desiredOppRotation:'P4',oppStartPhase:'serve',oppStartRotation:'P2'}};
let state=load(),pendingImport=[];
function clone(v){return JSON.parse(JSON.stringify(v))}function uid(){return crypto?.randomUUID?.()||'id-'+Date.now()+Math.random()}function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'null');return p?{...clone(blank),...p,filters:{...blank.filters,...p.filters},match:{...blank.match,...p.match},quick:{...blank.quick,...p.quick}}:clone(blank)}catch{return clone(blank)}}function save(){localStorage.setItem(KEY,JSON.stringify(state));const e=document.querySelector('#saveStatus');if(e){e.textContent='Salvato';setTimeout(()=>e.textContent='Locale',700)}}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function opp(p){return p==='serve'?'receive':'serve'}function nextRot(r){return ROTATIONS[(ROTATIONS.indexOf(r)+1)%6]}
function cycle(ourPhase,ourRotation,oppRotation){let a=ourPhase,b=opp(ourPhase),ar=ourRotation,br=oppRotation,out=[];for(let n=1;n<=12;n++){out.push({n,ourPhase:a,ourRotation:ar,oppPhase:b,oppRotation:br});if(a==='receive')ar=nextRot(ar);if(b==='receive')br=nextRot(br);a=opp(a);b=opp(b)}return out}
function findSituation(c,p,r){return c.find(x=>x.ourPhase===p&&x.ourRotation===r)||null}
function solveInverse(q){const startPhase=opp(q.oppStartPhase);for(const sr of ROTATIONS){const c=cycle(startPhase,sr,q.oppStartRotation);const hit=c.find(x=>x.ourPhase===q.desiredOurPhase&&x.ourRotation===q.desiredOurRotation&&x.oppRotation===q.desiredOppRotation);if(hit)return{ourStartPhase:startPhase,ourStartRotation:sr,hit}}return null}
function season(id){return state.seasons.find(x=>x.id===id)}function comp(id){return state.competitions.find(x=>x.id===id)}function team(id){return state.teams.find(x=>x.id===id)}function player(t,id){return t?.roster.find(x=>x.id===id)}function playerLabel(t,id){const p=player(t,id);return p?`${p.number?'#'+p.number+' ':''}${p.name}${p.role?' · '+p.role:''}`:'—'}
function ensureSeason(name){name=name.trim();let x=state.seasons.find(s=>s.name.toLowerCase()===name.toLowerCase());if(!x){x={id:uid(),name};state.seasons.push(x)}return x}function ensureComp(name,seasonId){name=name.trim();let x=state.competitions.find(c=>c.seasonId===seasonId&&c.name.toLowerCase()===name.toLowerCase());if(!x){x={id:uid(),name,seasonId};state.competitions.push(x)}return x}function ensureTeam(name,seasonId,competitionId){let x=state.teams.find(t=>t.name.toLowerCase()===name.toLowerCase()&&t.seasonId===seasonId&&t.competitionId===competitionId);if(!x){x={id:uid(),name,seasonId,competitionId,roster:[],lineup:Object.fromEntries(SLOTS.map(s=>[s,'']))};state.teams.push(x)}return x}
function role(v){const x=String(v||'').trim().toUpperCase();if(['S','P','PALLEGGIATORE','ALZATORE','SETTER'].includes(x))return'S';if(['OP','O','OPPOSTO','OPPOSITE'].includes(x))return'OP';if(['OH','S1','S2','SCHIACCIATORE','SCHIACCIATORE RICEVITORE','OUTSIDE'].includes(x))return'OH';if(['MB','C','C1','C2','CENTRALE','MIDDLE'].includes(x))return'MB';if(['L','LIBERO'].includes(x))return'L';return x||'OH'}
function physical(t,r){const shift=ROTATIONS.indexOf(r),out={};for(const[z0,slot]of Object.entries(BASE_P1)){let z=+z0;for(let i=0;i<shift;i++)z=z===1?6:z-1;out[z]={slot,playerId:t?.lineup?.[slot]||'',player:player(t,t?.lineup?.[slot])}}return out}function court(t,r){if(!t)return null;const pos=physical(t,r);return{pos,front:[4,3,2].map(z=>pos[z]),back:[5,6,1].map(z=>pos[z]),server:pos[1]}}
function switchView(n){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelector('#view-'+n)?.classList.add('active');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===n));if(n==='data')renderData();if(n==='teams')renderTeams();if(n==='match')renderMatch();if(n==='quick')renderQuick()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));
function picker(el,val,cb){el.innerHTML='';ROTATIONS.forEach(r=>{const b=document.createElement('button');b.textContent=r;b.className=r===val?'active':'';b.onclick=()=>{cb(r);picker(el,r,cb)};el.appendChild(b)})}function segment(el,val,cb){el.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.phase===val);b.onclick=()=>{cb(b.dataset.phase);segment(el,b.dataset.phase,cb)}})}function seasonOptions(v='',all='Seleziona stagione'){return`<option value="">${all}</option>`+state.seasons.map(s=>`<option value="${s.id}" ${s.id===v?'selected':''}>${esc(s.name)}</option>`).join('')}function compOptions(sid,v='',all='Seleziona competizione'){return`<option value="">${all}</option>`+state.competitions.filter(c=>!sid||c.seasonId===sid).map(c=>`<option value="${c.id}" ${c.id===v?'selected':''}>${esc(c.name)}</option>`).join('')}
function renderData(){countSeasons.textContent=state.seasons.length;countCompetitions.textContent=state.competitions.length;countTeams.textContent=state.teams.length;countPlayers.textContent=state.teams.reduce((n,t)=>n+t.roster.length,0);seasonList.innerHTML=state.seasons.length?state.seasons.map(s=>`<span class="chip">${esc(s.name)}</span>`).join(''):'<span class="muted">Nessuna stagione.</span>';competitionSeason.innerHTML=seasonOptions(competitionSeason.value,'Seleziona');competitionList.innerHTML=state.competitions.length?state.competitions.map(c=>`<span class="chip">${esc(season(c.seasonId)?.name||'—')} · ${esc(c.name)}</span>`).join(''):'<span class="muted">Nessuna competizione.</span>'}
addSeason.onclick=()=>{const n=seasonName.value.trim();if(!n)return;ensureSeason(n);seasonName.value='';save();renderData();renderTeams();renderMatch()};addCompetition.onclick=()=>{if(!competitionSeason.value||!competitionName.value.trim())return;ensureComp(competitionName.value.trim(),competitionSeason.value);competitionName.value='';save();renderData();renderTeams();renderMatch()};
downloadTemplate.onclick=()=>{const txt='stagione;competizione;squadra;numero;nome;ruolo\n2026/27;SuperLega;SIR SUSA SCai Perugia;6;Simone Giannelli;S\n';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/csv'}));a.download='MATCH-UP_modello_giocatori.csv';a.click();URL.revokeObjectURL(a.href)};
function parseCsv(text){const rows=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(rows.length<2)return[];const d=rows[0].split(';').length>=rows[0].split(',').length?';':',';const h=rows[0].split(d).map(x=>x.trim().toLowerCase());return rows.slice(1).map(r=>{const v=r.split(d).map(x=>x.trim().replace(/^"|"$/g,'')),o={};h.forEach((k,i)=>o[k]=v[i]||'');return o}).filter(x=>x.stagione&&x.competizione&&x.squadra&&x.nome)}
csvFile.onchange=async()=>{const f=csvFile.files?.[0];if(!f)return;pendingImport=parseCsv(await f.text());importPreview.innerHTML=pendingImport.length?`Pronte <b>${pendingImport.length}</b> righe da importare.`:'Nessuna riga valida.';confirmImport.classList.toggle('hidden',!pendingImport.length)};confirmImport.onclick=()=>{pendingImport.forEach(r=>{const s=ensureSeason(r.stagione),c=ensureComp(r.competizione,s.id),t=ensureTeam(r.squadra,s.id,c.id);if(!t.roster.some(p=>String(p.number)===String(r.numero)&&p.name.toLowerCase()===r.nome.toLowerCase()))t.roster.push({id:uid(),number:r.numero,name:r.nome,role:role(r.ruolo)})});pendingImport=[];confirmImport.classList.add('hidden');importPreview.textContent='Import completato.';save();renderData();renderTeams();renderMatch()};
function renderTeams(){teamFilterSeason.innerHTML=seasonOptions(state.filters.seasonId,'Tutte');teamFilterCompetition.innerHTML=compOptions(state.filters.seasonId,state.filters.competitionId,'Tutte');teamFilterSeason.onchange=()=>{state.filters.seasonId=teamFilterSeason.value;state.filters.competitionId='';save();renderTeams()};teamFilterCompetition.onchange=()=>{state.filters.competitionId=teamFilterCompetition.value;save();renderTeams()};const arr=state.teams.filter(t=>(!state.filters.seasonId||t.seasonId===state.filters.seasonId)&&(!state.filters.competitionId||t.competitionId===state.filters.competitionId));teamsList.classList.remove('empty-state');teamsList.innerHTML=arr.length?arr.map(t=>`<button data-id="${t.id}" class="${t.id===state.selectedTeamId?'active':''}"><b>${esc(t.name)}</b><br><small>${esc(season(t.seasonId)?.name||'')} · ${esc(comp(t.competitionId)?.name||'')}</small></button>`).join(''):'<div class="empty-state">Nessuna squadra salvata.</div>';teamsList.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.selectedTeamId=b.dataset.id;save();renderTeams()});const t=team(state.selectedTeamId);teamEditor.innerHTML=t?teamEditorHtml(t):'<div class="empty-state">Crea o seleziona una squadra.</div>';if(t)bindTeamEditor(t)}
function teamEditorHtml(t){return`<div class="team-head"><div><div class="eyebrow">${esc(season(t.seasonId)?.name||'')} · ${esc(comp(t.competitionId)?.name||'')}</div><h3>${esc(t.name)}</h3></div><button class="btn danger" id="deleteTeam">Elimina</button></div><h3>Roster</h3><div class="player-form"><input id="pNum" placeholder="#"><input id="pName" placeholder="Nome e cognome"><select id="pRole"><option>S</option><option>OP</option><option>OH</option><option>MB</option><option>L</option></select><button class="btn primary" id="addPlayer">Aggiungi</button></div><div id="rosterWrap"></div><hr><h3>Sestetto base</h3><p class="muted">P1 è definita dalla posizione dell’alzatore: Z1=P, Z2=S1, Z3=C2, Z4=O, Z5=S2, Z6=C1.</p><div class="lineup-editor" id="lineupEditor"></div><div id="p1Court"></div>`}
function bindTeamEditor(t){deleteTeam.onclick=()=>{if(confirm('Eliminare questa squadra?')){state.teams=state.teams.filter(x=>x.id!==t.id);state.selectedTeamId=null;save();renderTeams()}};addPlayer.onclick=()=>{if(!pName.value.trim())return;t.roster.push({id:uid(),number:pNum.value.trim(),name:pName.value.trim(),role:pRole.value});save();renderTeams()};renderRoster(t);renderLineup(t);renderP1(t)}
function renderRoster(t){rosterWrap.innerHTML=t.roster.length?`<table class="roster-table"><thead><tr><th>#</th><th>Nome</th><th>Ruolo</th><th></th></tr></thead><tbody>${t.roster.map(p=>`<tr><td>${esc(p.number)}</td><td>${esc(p.name)}</td><td>${esc(p.role)}</td><td><button class="btn" data-del="${p.id}">×</button></td></tr>`).join('')}</tbody></table>`:'<p class="muted">Nessun giocatore.</p>';rosterWrap.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{const id=b.dataset.del;t.roster=t.roster.filter(p=>p.id!==id);SLOTS.forEach(s=>{if(t.lineup[s]===id)t.lineup[s]=''});save();renderTeams()})}
function renderLineup(t){lineupEditor.innerHTML='';SLOTS.forEach(s=>{const d=document.createElement('div');d.className='lineup-slot';d.innerHTML=`<b>${s} · ${SLOT_ROLE[s]}</b>`;const sel=document.createElement('select');sel.innerHTML='<option value="">—</option>'+t.roster.filter(p=>p.role===SLOT_ROLE[s]).map(p=>`<option value="${p.id}">${esc(playerLabel(t,p.id))}</option>`).join('');sel.value=t.lineup[s]||'';sel.onchange=()=>{const id=sel.value;if(id)SLOTS.forEach(k=>{if(k!==s&&t.lineup[k]===id)t.lineup[k]=''});t.lineup[s]=id;save();renderLineup(t);renderP1(t)};d.appendChild(sel);lineupEditor.appendChild(d)})}
function renderP1(t){const p=physical(t,'P1');p1Court.innerHTML=`<div class="court-title">P1 · ALZATORE IN ZONA 1</div><div class="court-net">RETE</div><div class="court-grid">${[4,3,2,5,6,1].map(z=>`<div><b>Z${z} · ${p[z].slot}</b><span>${esc(playerLabel(t,p[z].playerId))}</span></div>`).join('')}</div>`}
newTeamBtn.onclick=()=>{newTeamSeason.innerHTML=seasonOptions(state.filters.seasonId,'Seleziona');newTeamCompetition.innerHTML=compOptions(newTeamSeason.value,'','Seleziona');newTeamSeason.onchange=()=>newTeamCompetition.innerHTML=compOptions(newTeamSeason.value,'','Seleziona');newTeamName.value='';teamDialog.showModal()};confirmNewTeam.onclick=e=>{e.preventDefault();if(!newTeamSeason.value||!newTeamCompetition.value||!newTeamName.value.trim())return;const t=ensureTeam(newTeamName.value.trim(),newTeamSeason.value,newTeamCompetition.value);state.selectedTeamId=t.id;save();teamDialog.close();renderTeams()};
function eligibleTeams(){return state.teams.filter(t=>(!state.match.seasonId||t.seasonId===state.match.seasonId)&&(!state.match.competitionId||t.competitionId===state.match.competitionId))}
function renderMatch(){matchSeasonSelect.innerHTML=seasonOptions(state.match.seasonId);matchCompetitionSelect.innerHTML=compOptions(state.match.seasonId,state.match.competitionId);matchSeasonSelect.onchange=()=>{state.match.seasonId=matchSeasonSelect.value;state.match.competitionId='';state.match.ourTeamId=state.match.oppTeamId=null;save();renderMatch()};matchCompetitionSelect.onchange=()=>{state.match.competitionId=matchCompetitionSelect.value;state.match.ourTeamId=state.match.oppTeamId=null;save();renderMatch()};[['ourTeamSelect','ourTeamId'],['oppTeamSelect','oppTeamId']].forEach(([id,key])=>{const el=document.getElementById(id);el.innerHTML='<option value="">Seleziona squadra</option>'+eligibleTeams().map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');el.value=state.match[key]||'';el.onchange=()=>{state.match[key]=el.value||null;save();renderMatchLineups()}});segment(ourPhaseSegment,state.match.ourPhase,p=>{state.match.ourPhase=p;save();oppPhaseLabel.textContent=PHASE[opp(p)];cyclePanel.classList.add('hidden')});oppPhaseLabel.textContent=PHASE[opp(state.match.ourPhase)];picker(ourRotationPicker,state.match.ourRotation,r=>{state.match.ourRotation=r;save();renderMatchLineups();cyclePanel.classList.add('hidden')});picker(oppRotationPicker,state.match.oppRotation,r=>{state.match.oppRotation=r;save();renderMatchLineups();cyclePanel.classList.add('hidden')});renderMatchLineups()}
function miniCourt(t,r){if(!t)return'<div class="muted">Nessuna squadra selezionata.</div>';const c=court(t,r);return`<div class="mini-court-head">${r} · alzatore in zona ${r.slice(1)}</div><div class="mini-court-grid">${[4,3,2,5,6,1].map(z=>`<div><b>Z${z} · ${c.pos[z].slot}</b><span>${esc(playerLabel(t,c.pos[z].playerId))}</span></div>`).join('')}</div>`}
function renderMatchLineups(){matchLineups.innerHTML=[['NOI',team(state.match.ourTeamId),state.match.ourRotation],['LORO',team(state.match.oppTeamId),state.match.oppRotation]].map(([l,t,r])=>`<div class="lineup-card"><h4>${l}${t?' · '+esc(t.name):''}</h4>${miniCourt(t,r)}</div>`).join('')}
invertStart.onclick=()=>{state.match.ourPhase=opp(state.match.ourPhase);save();renderMatch()};generateCycle.onclick=()=>{if(!state.match.ourTeamId||!state.match.oppTeamId){alert('Seleziona entrambe le squadre.');return}cyclePanel.classList.remove('hidden');cycleTitle.textContent=`NOI ${SHORT[state.match.ourPhase]} ${state.match.ourRotation} · LORO ${SHORT[opp(state.match.ourPhase)]} ${state.match.oppRotation}`;renderCycle(cycleList,cycle(state.match.ourPhase,state.match.ourRotation,state.match.oppRotation))};
function renderCycle(root,c){const a=team(state.match.ourTeamId),b=team(state.match.oppTeamId);root.innerHTML=c.map(x=>{const ac=court(a,x.ourRotation),bc=court(b,x.oppRotation);return`<div class="cycle-row-rich"><div class="cycle-top"><div class="cycle-num">${x.n}</div><div class="state-chip ${x.ourPhase}">NOI ${SHORT[x.ourPhase]} ${x.ourRotation}</div><div class="arrow">${x.ourPhase==='serve'?'→':'←'}</div><div class="state-chip ${x.oppPhase}">LORO ${SHORT[x.oppPhase]} ${x.oppRotation}</div></div><div class="cycle-detail"><div><b>NOI DAVANTI</b><span>${ac?ac.front.map(y=>y.slot+(y.player?.number?' #'+y.player.number:'')).join(' · '):'—'}</span></div><div><b>LORO DAVANTI</b><span>${bc?bc.front.map(y=>y.slot+(y.player?.number?' #'+y.player.number:'')).join(' · '):'—'}</span></div><div><b>BATTITORE</b><span>${x.ourPhase==='serve'?(ac?playerLabel(a,ac.server.playerId):'—'):(bc?playerLabel(b,bc.server.playerId):'—')}</span></div></div></div>`}).join('')}
function renderQuick(){currentStartSummary.textContent=state.match.ourTeamId&&state.match.oppTeamId?`PARTENZA · NOI ${SHORT[state.match.ourPhase]} ${state.match.ourRotation} · LORO ${SHORT[opp(state.match.ourPhase)]} ${state.match.oppRotation}`:'Imposta prima una partita.';segment(queryPhaseSegment,state.quick.queryPhase,p=>{state.quick.queryPhase=p;save();updateWhere()});picker(queryRotationPicker,state.quick.queryRotation,r=>{state.quick.queryRotation=r;save();updateWhere()});segment(desiredOurPhase,state.quick.desiredOurPhase,p=>{state.quick.desiredOurPhase=p;desiredOppPhaseLabel.textContent=PHASE[opp(p)];save()});desiredOppPhaseLabel.textContent=PHASE[opp(state.quick.desiredOurPhase)];picker(desiredOurRotation,state.quick.desiredOurRotation,r=>{state.quick.desiredOurRotation=r;save()});picker(desiredOppRotation,state.quick.desiredOppRotation,r=>{state.quick.desiredOppRotation=r;save()});segment(oppStartPhaseForInverse,state.quick.oppStartPhase,p=>{state.quick.oppStartPhase=p;save()});picker(oppStartRotationForInverse,state.quick.oppStartRotation,r=>{state.quick.oppStartRotation=r;save()});updateWhere()}
function updateWhere(){const strong=whereAnswer.querySelector('strong');if(!state.match.ourTeamId||!state.match.oppTeamId){strong.textContent='—';return}const h=findSituation(cycle(state.match.ourPhase,state.match.ourRotation,state.match.oppRotation),state.quick.queryPhase,state.quick.queryRotation);strong.textContent=h?`LORO ${SHORT[h.oppPhase]} ${h.oppRotation}`:'NON TROVATO'}
document.querySelectorAll('.quick-mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.quick-mode').forEach(x=>x.classList.toggle('active',x===b));quickWherePanel.classList.toggle('hidden',b.dataset.mode!=='where');quickInversePanel.classList.toggle('hidden',b.dataset.mode!=='inverse');quickCyclePanel.classList.toggle('hidden',b.dataset.mode!=='cycle')});solveInverse.onclick=()=>{const r=solveInverse(state.quick);inverseAnswer.querySelector('strong').textContent=r?`${SHORT[r.ourStartPhase]} ${r.ourStartRotation}`:'NESSUNA SOLUZIONE'};quickShowCycle.onclick=()=>{if(!state.match.ourTeamId||!state.match.oppTeamId){quickCycleList.innerHTML='<p class="muted">Imposta prima una partita.</p>';return}renderCycle(quickCycleList,cycle(state.match.ourPhase,state.match.ourRotation,state.match.oppRotation))};
resetLocal.onclick=()=>{if(confirm('Cancellare tutti i dati locali?')){localStorage.removeItem(KEY);state=clone(blank);save();renderData();renderTeams();renderMatch();renderQuick()}};
renderData();renderTeams();renderMatch();renderQuick();
